version: "3.8"

services:

  trace-emulator:
    env_file:
      - .env
    build:
      dockerfile: src/Dockerfile
      context: .
    image: trace-emulator-img
    ports:
      - "${PORT}:8000"
    restart: always

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "127.0.0.1:11211:11211"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./src/app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./src/app/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./src/app/grafana/config.monitoring
